# Generated by Django 5.0.6 on 2024-11-28 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=6, verbose_name='姓名')),
                ('phone_num', models.CharField(max_length=12, null=True, verbose_name='电话号码')),
            ],
            options={
                'abstract': False,
            },
            bases=('consumer.customuser',),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='考试标题')),
                ('content', models.TextField(verbose_name='考试描述')),
                ('starttime', models.DateTimeField(verbose_name='开始时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('classes', models.ManyToManyField(blank=True, to='teacher_app.class', verbose_name='参与考试的班级')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.teacher', verbose_name='发布教师')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('memory_limit', models.IntegerField(default=0, verbose_name='内存限制')),
                ('time_limit', models.IntegerField(default=0, verbose_name='时间限制')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher_app.exam', verbose_name='考试')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='测试输入')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_testcases', to='teacher_app.examquestion', verbose_name='题目')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='练习标题')),
                ('content', models.TextField(verbose_name='练习描述')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('classes', models.ManyToManyField(blank=True, to='teacher_app.class', verbose_name='参与练习的班级')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.teacher', verbose_name='发布教师')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('memory_limit', models.IntegerField(default=0, verbose_name='内存限制')),
                ('time_limit', models.IntegerField(default=0, verbose_name='时间限制')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher_app.exercise', verbose_name='练习')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='测试输入')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_testcases', to='teacher_app.exercisequestion', verbose_name='题目')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('recipients', models.ManyToManyField(to='teacher_app.class', verbose_name='接收班级')),
            ],
        ),
        migrations.CreateModel(
            name='ReportScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalscore', models.IntegerField(verbose_name='总分')),
                ('contents', models.IntegerField(verbose_name='内容得分')),
                ('firstrow', models.IntegerField(verbose_name='首行得分')),
                ('fontsize', models.IntegerField(verbose_name='字体大小得分')),
                ('image', models.IntegerField(verbose_name='图片得分')),
                ('pagenum', models.IntegerField(verbose_name='页数得分')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_scores', to='teacher_app.teacher', verbose_name='教师')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher', verbose_name='教师'),
        ),
    ]
