# Generated by Django 5.0.6 on 2024-11-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0003_adminnotification_administrator_and_more'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='administrator_app.administrator', verbose_name='课程负责人'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher', verbose_name='发布教师'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher', verbose_name='发布教师'),
        ),
    ]
