# Generated by Django 5.1a1 on 2024-06-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0021_alter_exercise_content_alter_exercise_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='测试输入')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_testcases', to='teacher_app.examquestion', verbose_name='题目')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='测试输入')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_testcases', to='teacher_app.exercisequestion', verbose_name='题目')),
            ],
        ),
    ]
