# Generated by Django 5.0.6 on 2024-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0023_remove_examquestion_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='published_at',
        ),
        migrations.AddField(
            model_name='exam',
            name='starttime',
            field=models.DateTimeField(default=None, verbose_name='开始时间'),
        ),
    ]
