# Generated by Django 5.0.6 on 2024-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0024_remove_exam_published_at_exam_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='starttime',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
