# Generated by Django 5.0.6 on 2024-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='考试标题')),
                ('content', models.TextField(verbose_name='考试描述')),
                ('starttime', models.DateTimeField(verbose_name='开始时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
            ],
        ),
        migrations.CreateModel(
            name='AdminExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('memory_limit', models.IntegerField(default=0, verbose_name='内存限制')),
                ('time_limit', models.IntegerField(default=0, verbose_name='时间限制')),
            ],
        ),
        migrations.CreateModel(
            name='AdminExamQuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='测试输入')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
            ],
        ),
    ]
