# Generated by Django 5.0.6 on 2024-11-28 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator_app', '0001_initial'),
        ('consumer', '0001_initial'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=6, verbose_name='姓名')),
                ('phone_num', models.CharField(max_length=12, null=True, verbose_name='电话号码')),
            ],
            options={
                'abstract': False,
            },
            bases=('consumer.customuser',),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
        migrations.AddField(
            model_name='adminexam',
            name='classes',
            field=models.ManyToManyField(blank=True, to='teacher_app.class', verbose_name='参与考试的班级'),
        ),
        migrations.AddField(
            model_name='adminexamquestion',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='administrator_app.adminexam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='adminexamquestiontestcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_testcases', to='administrator_app.adminexamquestion', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='adminexam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator_app.administrator', verbose_name='发布教师'),
        ),
        migrations.CreateModel(
            name='ProgrammingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.administrator', verbose_name='发布教师')),
            ],
        ),
    ]
