# Generated by Django 5.1a1 on 2024-06-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0015_alter_administrator_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExamQuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='测试输入')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_testcases', to='administrator_app.adminexamquestion', verbose_name='题目')),
            ],
        ),
    ]
