# Generated by Django 5.0.6 on 2024-07-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0016_adminexamquestiontestcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexamquestion',
            name='answer',
        ),
    ]
