# Generated by Django 5.0.6 on 2024-07-15 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0017_remove_adminexamquestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminexam',
            name='published_at',
        ),
        migrations.AddField(
            model_name='adminexam',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
