# Generated by Django 5.0.6 on 2024-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0018_remove_adminexam_published_at_adminexam_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminexam',
            name='starttime',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
