# Generated by Django 5.0.6 on 2024-10-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator_app', '0019_alter_adminexam_starttime'),
        ('teacher_app', '0025_alter_exam_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=255, verbose_name='提交编号')),
                ('student_id', models.CharField(max_length=255, verbose_name='学号')),
                ('result', models.CharField(max_length=255, verbose_name='结果')),
                ('memory', models.IntegerField(verbose_name='内存')),
                ('time', models.IntegerField(verbose_name='耗时')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('code_length', models.IntegerField(verbose_name='代码长度')),
                ('submission_time', models.DateTimeField(verbose_name='提交时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.exam', verbose_name='考试')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.examquestion', verbose_name='考试题目')),
            ],
        ),
        migrations.CreateModel(
            name='GradeExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=255, verbose_name='提交编号')),
                ('student_id', models.CharField(max_length=255, verbose_name='学号')),
                ('result', models.CharField(max_length=255, verbose_name='结果')),
                ('memory', models.IntegerField(verbose_name='内存')),
                ('time', models.IntegerField(verbose_name='耗时')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('code_length', models.IntegerField(verbose_name='代码长度')),
                ('submission_time', models.DateTimeField(verbose_name='提交时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.adminexam', verbose_name='考试')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.adminexamquestion', verbose_name='考试题目')),
            ],
        ),
    ]
