# Generated by Django 5.0.6 on 2024-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexamsubmission',
            name='submission_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='提交编号'),
        ),
        migrations.AlterField(
            model_name='gradeexamsubmission',
            name='submission_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='提交编号'),
        ),
    ]
