# Generated by Django 5.0.6 on 2024-10-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions_app', '0002_alter_classexamsubmission_submission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classexamsubmission',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='gradeexamsubmission',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='classexamsubmission',
            name='language',
            field=models.CharField(max_length=10, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='classexamsubmission',
            name='result',
            field=models.CharField(max_length=10, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='classexamsubmission',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='gradeexamsubmission',
            name='language',
            field=models.CharField(max_length=10, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='gradeexamsubmission',
            name='result',
            field=models.CharField(max_length=10, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='gradeexamsubmission',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='学号'),
        ),
    ]
