# Generated by Django 5.0.6 on 2024-11-28 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator_app', '0002_initial'),
        ('consumer', '0001_initial'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=6, verbose_name='姓名')),
                ('class_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher_app.class', verbose_name='班级')),
            ],
            options={
                'abstract': False,
            },
            bases=('consumer.customuser',),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='得分')),
                ('adminexam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='administrator_app.adminexam', verbose_name='年级考试')),
                ('adminexam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='administrator_app.adminexamquestion', verbose_name='年级考试题')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.exam', verbose_name='考试')),
                ('exam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.examquestion', verbose_name='考试题')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.exercise', verbose_name='练习')),
                ('exercise_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.exercisequestion', verbose_name='练习题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_question_completions', to='teacher_app.exercise', verbose_name='练习')),
                ('exercise_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_question_completions', to='teacher_app.exercisequestion', verbose_name='练习题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_question_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to='teacher_app.exercise', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_completions', to='teacher_app.exam', verbose_name='考试')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_completions', to='teacher_app.examquestion', verbose_name='考试题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_completions', to='teacher_app.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='AdminExamQuestionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('adminexam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_question_completions', to='administrator_app.adminexam', verbose_name='考试')),
                ('adminexam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_question_completions', to='administrator_app.adminexamquestion', verbose_name='考试题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_question_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='AdminExamCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('adminexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_completions', to='administrator_app.adminexam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='代码')),
                ('question_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目类型')),
                ('question_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_codes', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目类型')),
                ('question_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目id')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('passed_tests', models.IntegerField(blank=True, null=True)),
                ('testcases', models.IntegerField(blank=True, default=0, null=True)),
                ('execution_time', models.IntegerField(default=0)),
                ('max_memory', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
