# Generated by Django 5.0.6 on 2024-07-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0024_alter_score_adminexam_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='代码')),
                ('question_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目类型')),
                ('question_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_codes', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
