# Generated by Django 5.0.6 on 2024-07-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0025_studentcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目类型')),
                ('question_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='题目id')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('passed_tests', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('testresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_results', to='student_app.testresult')),
            ],
        ),
    ]
