# Generated by Django 5.0.6 on 2024-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0026_testresult_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='testcases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
