# Generated by Django 5.0.6 on 2024-07-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0027_testresult_testcases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testcase',
        ),
    ]
