# Generated by Django 5.0.6 on 2024-07-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0019_alter_adminexam_starttime'),
        ('student_app', '0028_delete_testcase'),
        ('teacher_app', '0025_alter_exam_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexamquestioncompletion',
            name='adminexam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_question_completions', to='administrator_app.adminexam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='examquestioncompletion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_completions', to='teacher_app.exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='exercisequestioncompletion',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_question_completions', to='teacher_app.exercise', verbose_name='练习'),
        ),
        migrations.AddField(
            model_name='score',
            name='adminexam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='administrator_app.adminexam', verbose_name='年级考试'),
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='score',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.exercise', verbose_name='练习'),
        ),
    ]
