# Generated by Django 5.0.6 on 2024-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0029_adminexamquestioncompletion_adminexam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='max_memory',
            field=models.IntegerField(default=0),
        ),
    ]
