# Generated by Django 5.0.6 on 2024-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingCodeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='特征值')),
                ('cosine_similarity', models.FloatField(blank=True, null=True, verbose_name='余弦相似度')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingReportFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='特征值')),
                ('cosine_similarity', models.FloatField(blank=True, null=True, verbose_name='余弦相似度')),
            ],
        ),
        migrations.CreateModel(
            name='ReportStandardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_score', models.IntegerField(verbose_name='报告规范性得分')),
            ],
        ),
    ]
