# Generated by Django 5.0.6 on 2024-11-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BERT_app', '0001_initial'),
        ('administrator_app', '0002_initial'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingcodefeature',
            name='programming_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_code_features', to='administrator_app.programmingexercise', verbose_name='练习题'),
        ),
        migrations.AddField(
            model_name='programmingcodefeature',
            name='similar_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_code_students', to='student_app.student', verbose_name='相似的学生用户'),
        ),
        migrations.AddField(
            model_name='programmingcodefeature',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programming_code_features', to='student_app.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='programmingreportfeature',
            name='programming_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_report_features', to='administrator_app.programmingexercise', verbose_name='练习题'),
        ),
        migrations.AddField(
            model_name='programmingreportfeature',
            name='similar_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_report_students', to='student_app.student', verbose_name='相似的学生用户'),
        ),
        migrations.AddField(
            model_name='programmingreportfeature',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programming_report_features', to='student_app.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='reportstandardscore',
            name='programming_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_standards', to='administrator_app.programmingexercise', verbose_name='练习题'),
        ),
        migrations.AddField(
            model_name='reportstandardscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_standards', to='student_app.student', verbose_name='学生'),
        ),
    ]
